apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: zommojun
spec:
  type: NodePort
  selector:
    app: server
  ports:
  - name: http
    port: 30011
    targetPort: 30011
    nodePort: 30011

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: zommojun
  labels:
    deploy: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: bot
        image: commojun/zommojun
        ports:
        - containerPort: 30011
        readinessProbe:
          httpGet:
            path: /ping
            port: 30011
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
        envFrom:
        - secretRef:
            name: zommojun-secret
      - name: tunnel
        image: cloudflare/cloudflared
        command:
          - cloudflared
          - tunnel
          - run
        envFrom:
        - secretRef:
            name: zommojun-secret
